In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])

In [4]:
print(a, type(a))

[0 1 2 3] <class 'numpy.ndarray'>


In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
L = range(1000)

In [7]:
print(L, type(L))

range(0, 1000) <class 'range'>


In [8]:
%timeit [i**2 for i in L]

278 µs ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit [i**2 for i in a]
%timeit a**2  

171 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
875 ns ± 80.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
# Learn about creating numpy array 1-D

arr = np.array([1,2,3])

print(arr.ndim)  # dimension of array
print(arr.shape) # number of rows and cols
print(len(arr)) # length of first dimension

1
(3,)
3


In [11]:
# Learn about creating numpy array 2-D

arr = np.array([[1,2,3], [4,5,6]])

print(arr.ndim)  # dimension of array
print(arr.shape) # number of rows, cols
print(len(arr)) # length of first dimension

2
(2, 3)
2


In [12]:
# Learn about creating numpy array 3-D

arr = np.array([[[1,2,3], [4, 5, 6]], [[7,8,9], [10, 11, 12]]])

print(arr.ndim)  # dimension of array
print(arr.shape) # number of rows and cols
print(len(arr)) # length of first dimension

3
(2, 2, 3)
2


In [13]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [14]:
np.linspace(1, 10, 5)  # divide line from 1 to 10 in 5 equal parts

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
a = np.ones((3,3))
print(a.dtype) # default data type is float 
print(a)

float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
b = np.zeros((3,3))
print(b.dtype) # default data type is float 
print(b)

float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a = np.eye(3,3)  # create identity matrix with diagonal's are only 1
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
b = np.diag([1,2,3,4]) # diagonal matrix
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
print(np.diag(b))

[1 2 3 4]


In [20]:
# create uniform random number
a = np.random.rand(4)
a

array([0.09274334, 0.07077579, 0.91747349, 0.27612518])

In [21]:
# return a sample normal random number
a = np.random.randn(4)
a

array([ 0.43026941,  0.54591715,  0.29640344, -0.60800864])

In [22]:
a = np.array([1,2,3,4])
print(a.dtype)
print(a)

int64
[1 2 3 4]


In [23]:
a = np.array([1,2,3,4], dtype='float64')
print(a.dtype)
print(a)

float64
[1. 2. 3. 4.]


In [24]:
# complex data type 
d = np.array([1+2j, 2+4j])
print(d.dtype)
print(d)

complex128
[1.+2.j 2.+4.j]


In [25]:
# boolean data type 
b = np.array([True, False, True, False])
print(b.dtype)
print(b)

bool
[ True False  True False]


In [26]:
s = np.array(['hello', 'there'])
print(s.dtype)
print(s)

<U5
['hello' 'there']


In [27]:
a = np.arange(10)
print(a[5])
a = np.diag([1,2,3]) # creates a diagonal matrix
print(a[2,2])
print(a)
a[2,1] = 5
print(a)

5
3
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [28]:
a = np.arange(10)
print(a[1:8:2]) # slicing and returning sub-array
print(a[5:]) # from 5th index till end
print(a)
b = np.arange(5)
a[5:] = b[::-1]
print(a)

[1 3 5 7]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 4 3 2 1 0]


In [29]:
a = np.arange(10)
print(a)
b= a[::2]
print(b)
print(np.shares_memory(a, b))
b[0] = 33
print(a)

c = a[::2].copy()
print(np.shares_memory(a, c))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[33  1  2  3  4  5  6  7  8  9]
False


In [30]:
#fancy indexing
r = np.random.randint(0, 20, 15) # creates 15 random numbers between 0,20

mask = (r % 2 == 0)

# mask creates deep copy not views, so both arrays don't share memory
create_even_number = r[mask] # apply mask on every element in array
print(create_even_number) # returns just the even numbers

r[mask] = -1 # change even numbers to -1
print(r)

[14  6  8 16 12 16  4 12  0]
[-1  9 -1 -1 17 19  7 -1 -1 -1 15 13 -1 -1 -1]


In [31]:
a= np.arange(0, 100, 10) # create number from 0 to 99 with 10 gap

print(a)
b = a[[2, 3, 4, 2]] # extract indexes from a and create new array and store in b

print(b)

a[[9, 7]] = -200 # change indexes 9 and 7 in a array to value -200
print(a)

np.shares_memory(a, b)

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 40 20]
[   0   10   20   30   40   50   60 -200   80 -200]


False