In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
print(a+1) # element wise operation
print(a**2) # element wise operation

[2 3 4 5]
[ 1  4  9 16]


In [3]:
b = np.ones(4)+1
a-b   #substraction of arrays

array([-1.,  0.,  1.,  2.])

In [4]:
a * b  #Multiplication of arrays

array([2., 4., 6., 8.])

In [5]:
# Matrix Multiplication

c = np.diag([1,2,3,4])
print(c*c)

print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,3,8])
c = np.array([1,2,3,4])

print(a==b)  # element wise comparison
print(b>a)
print(np.array_equal(a,c)) # Also checks each element and return boolean
print(np.array_equal(a,b))

[False False  True False]
[ True  True False  True]
True
False


In [7]:
#logical Operations

a = np.array([1,0,0,1])
b = np.array([0,1,1,0])

print(np.logical_and(a, b))
print(np.logical_or(a,b))

[False False False False]
[ True  True  True  True]


In [8]:
a = np.arange(5)
print(a)

print(np.sin(a)) # return sin(a[0]) ... sin(a[4])
print(np.log(a))  # return log(a[0]) .... log(a[4])
print(np.exp(a))  # e^a[0] ... e^a[4]

[0 1 2 3 4]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


<ipython-input-8-f8ce813b7440>:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))  # return log(a[0]) .... log(a[4])


In [9]:
# shape mismatch

a = np.arange(4)
b = a+np.array([1,3])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [10]:
x = np.array([1,2,3,4])
print(np.sum(x))
print("sum :", x.sum())

10
sum : 10


In [11]:
x = np.array([[1,1],[2,2]])
print(x.sum(axis=0)) # sum of coloumns
print(x.sum(axis=1)) # sum of rows

[3 3]
[2 4]


In [12]:
x = np.array([1,2,3])
print("min element Index {}, element {}".format(x.argmin(), x.min()))
print("max element Index {}, element {}".format(x.argmax(), x.max()))


min element Index 0, element 1
max element Index 2, element 3


In [13]:
#logical operations
print(np.all([True, False, True, False]))   # Logical AND (Return True if all are True)
print(np.any([True, False, False, False])) # Logical OR (Return True if any is True)

False
True


In [14]:
a = np.zeros((50, 50))
print(np.any(a!=0))  # returns true if any one in matrix is True
a[0,4] = 1
print(np.any(a!=0))

False
True


In [15]:
print(np.all(a==a)) # returns true as all elements match

True


In [16]:
a = np.array([1,2,3,1])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

'''
  checks if all elements of a is less than or equal to b and returns boolean array
  and all elements of b is less than or equal to c and returns boolean array
  then perform AND operation on each element and returns boolean array then checks
  Logical OR with all() method and returns True if all the elements are True
'''

((a <= b) & (b <= c)).all() 


True

In [17]:
# statistics

x = np.array([1,2,3,1])
print(x.mean()) # average of all the elements
print(np.median(x)) # middle element if size of array is odd and average of two mid elements if size is even
print(x.std()) # standard deviation

1.75
1.5
0.82915619758885


In [18]:
y = np.array([[1,2,3], [4, 5, 6]])
print(np.median(y, axis=-1)) # calculate median of last dimension

# axis 0 -> columns
# axis 1 -> rows      # this is the last dimension so -1 also means rows

[2. 5.]


In [19]:
# Numpy Broadcasting

a = np.tile(np.arange(4), (3, 1))  # tiles generally replicate the rows and cols
# (3,1) means replicate row which we got from np.arrange() 3 times and each column 1 time 
print(a)

print("************* ")
print(a.T) # transpose of matrix
a = a.T

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
************* 
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [20]:
b = np.array([0,1,2])

print(a+b) # this will create tiles for b array and replicate rows 4 times to match with a and then add each elements

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [21]:
# In Numpy broadcasting, if we add two arrays if shapes are not matching it will add tiles

'''
  In Numpy broadcasting first shape has to be equal or less than in one dimension
  and in replication it will match both the shapes as same before adding them
'''

a = np.arange(4)
print(a, a.shape)
a = a[:, np.newaxis]
print(a, a.shape) # Adds new axis and becomes 2D array with 4 rows and 1 cols

print(" ***** Addition with Numpy Broadcasting ****** ")

print(a+b)

[0 1 2 3] (4,)
[[0]
 [1]
 [2]
 [3]] (4, 1)
 ***** Addition with Numpy Broadcasting ****** 
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [26]:
# Array Shape Manipulation

a = np.array([[1,2,3], [4,5,6]])
print(a.ravel())  # flatten the array in 1-D 
a=a.T
print("*****")
print(a)
print("*****")
print(a.ravel())

[1 2 3 4 5 6]
*****
[[1 4]
 [2 5]
 [3 6]]
*****
[1 4 2 5 3 6]


In [23]:
a = np.array([[1,2,3,], [4,5,6]])
print(a)
b = a.ravel()
print(b)
b= b.reshape((2,3)) # reshaping not returning a copy but it does sometimes
print(b)

b[0,1] = 44    # a and b are pointing to same memory location, data is not copied into b
print("******** ")
print("Reshaping does not return a copy here")
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
******** 
Reshaping does not return a copy here
[[ 1 44  3]
 [ 4  5  6]]


In [24]:
a = np.zeros((2,3))
print(a.shape)
b = a.T.reshape(2,3)
print(b.shape)
b[0,1] = 22

print("Reshaping does return a copy here")
print(a)

(2, 3)
(2, 3)
Reshaping does return a copy here
[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
z = np.array([1,2,3])
print(z)

[1 2 3]


In [26]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [27]:
a = np.arange(4*3*2).reshape(4,3,2) # 3-D Matrix

# 4 x 3 x 2 -> means it is 4 matrix of ( 3 x 2 ) -> 3 rows and 2 cols

print(a, a.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] (4, 3, 2)


In [28]:
 print(a[0, 2, 1])  # Go to first matrix, 3rd row, 2nd column (as indices start from 0)

5


In [29]:
a = np.arange(4)
print(a)
a.resize((8,))
print(a, id(a))
b = a
print(b, id(b))

a.resize(9)  # won't allow to resize as another array is also referencing the same location



[0 1 2 3]
[0 1 2 3 0 0 0 0] 4710604208
[0 1 2 3 0 0 0 0] 4710604208


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [30]:
a = np.array([[4,2,6], [9,5,7]])
print(a)
%timeit b = np.sort(a, axis=1)
#print(b)

[[4 2 6]
 [9 5 7]]
2.32 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
%timeit a.sort(axis=1)
print(a)

490 ns ± 74.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[[2 4 6]
 [5 7 9]]


In [32]:
a = np.array([9,4, 8, 10])

j = np.argsort(a)

print(j) # returns indices order in which sorted data look like

print(a[j])

[1 2 0 3]
[ 4  8  9 10]
